onEvent('item.tags', event => {
    // 子弹
    event.add('sdnsammo:b_9mmra', 'contenttweaker:b_9mmra')
    event.add('sdnsammo:b_12gra', 'contenttweaker:b_12gra')
    event.add('sdnsammo:b_30_06ra', 'contenttweaker:b_30_06ra')
    event.add('sdnsammo:b_45acpra', 'contenttweaker:b_45acpra')
    event.add('sdnsammo:b_50aera', 'contenttweaker:b_50aera')
    event.add('sdnsammo:b_50bmgra', 'contenttweaker:b_50bmgra')
    event.add('sdnsammo:b_58x42ra', 'contenttweaker:b_58x42ra')
    event.add('sdnsammo:b_68x51furyra', 'contenttweaker:b_68x51furyra')
    event.add('sdnsammo:b_308ra', 'contenttweaker:b_308ra')
    event.add('sdnsammo:b_338ra', 'contenttweaker:b_338ra')
    event.add('sdnsammo:b_556x45ra', 'contenttweaker:b_556x45ra')
    event.add('sdnsammo:b_762x25ra', 'contenttweaker:b_762x25ra')
    event.add('sdnsammo:b_762x39ra', 'contenttweaker:b_762x39ra')
    event.add('sdnsammo:b_762x54ra', 'contenttweaker:b_762x54ra')
    // 蓝图
    event.add('sdnsmisc:blueprinta', 'contenttweaker:blueprinta')
    event.add('sdnsmisc:blueprintb', 'contenttweaker:blueprintb')
    event.add('sdnsmisc:blueprintc', 'contenttweaker:blueprintc')
    event.add('sdnsmisc:blueprintd', 'contenttweaker:blueprintd')
    event.add('sdnsmisc:blueprinte', 'contenttweaker:blueprinte')
    event.add('sdnsmisc:blueprintf', 'contenttweaker:blueprintf')
    // 手枪
    event.add('sdnsgunpart:pistol_slide', 'sevendaystomine:pistol_slide')
    event.add('sdnsgunpart:pistol_trigger', 'sevendaystomine:pistol_trigger')
    event.add('sdnsgunpart:pistol_grip', 'sevendaystomine:pistol_grip')
    // 冲锋枪
    event.add('sdnsgunpart:smg_barrel', 'sevendaystomine:mp5_barrel')
    event.add('sdnsgunpart:smg_trigger', 'sevendaystomine:mp5_trigger')
    event.add('sdnsgunpart:smg_stock', 'sevendaystomine:mp5_stock')
    // 步枪
    event.add('sdnsgunpart:rifle_barrel', 'sevendaystomine:hunting_rifle_barrel')
    event.add('sdnsgunpart:rifle_stock', 'sevendaystomine:hunting_rifle_stock')
    event.add('sdnsgunpart:rifle_bolt', 'sevendaystomine:hunting_rifle_bolt')
    event.add('sdnsgunpart:rifle_parts', 'sevendaystomine:rifle_parts')
    // 狙击步枪
    event.add('sdnsgunpart:sniper_rifle_barrel', 'sevendaystomine:sniper_rifle_barrel')
    event.add('sdnsgunpart:sniper_rifle_trigger', 'sevendaystomine:sniper_rifle_trigger')
    event.add('sdnsgunpart:sniper_rifle_stock', 'sevendaystomine:sniper_rifle_stock')
    // 霰弹枪
    event.add('sdnsgunpart:shotgun_barrel_short', 'sevendaystomine:shotgun_barrel_short')
    event.add('sdnsgunpart:shotgun_stock_short', 'sevendaystomine:shotgun_stock_short')
    event.add('sdnsgunpart:shotgun_receiver', 'sevendaystomine:shotgun_receiver')
    event.add('sdnsgunpart:shotgun_parts', 'sevendaystomine:shotgun_parts')
    event.add('sdnsgunpart:shotgun_barrel', 'sevendaystomine:shotgun_barrel')
    event.add('sdnsgunpart:shotgun_stock', 'sevendaystomine:shotgun_stock')
    // 玻璃
    event.add('sdnsmisc:glass', 'sevendaystomine:scrap_glass')
    // 废铁
    event.add('sdnsmisc:iron', 'sevendaystomine:scrap_iron')
    // 弓
    event.add('sdnsmisc:bow', ['minecraft:bow', 'sevendaystomine:crude_bow'])
    // 水瓶
    event.add('sdnsmisc:water_potion', 'minecraft:potion')
    })